# Generated by Django 6.0.5 on 2026-07-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_first_login_completed_user_otp_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('HOD', 'HOD'), ('MANAGEMENT', 'Management / AO'), ('PRINCIPAL', 'Principal'), ('DEAN_COMPUTING', 'Dean Computing')], default='FACULTY', max_length=20),
        ),
    ]
