services:
  - type: web
    name: function-system-backend
    env: python
    buildCommand: "./backend/build.sh"
    startCommand: "cd backend && gunicorn function_requirement_system.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "True"
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
