# Generated by Django 6.0.5 on 2026-07-31 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_remove_functionrequest_date_functionrequest_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD', 'Pending HOD Approval'), ('PENDING_DEAN', 'Pending Dean Approval'), ('PENDING_MANAGEMENT', 'Pending Management Approval'), ('PENDING_PRINCIPAL', 'Pending Principal Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30),
        ),
    ]
