# Generated by Django 6.0.5 on 2026-08-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_alter_functionrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionrequest',
            name='previous_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='functionrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD', 'Pending HOD Approval'), ('PENDING_DEAN', 'Pending Dean Approval'), ('PENDING_MANAGEMENT', 'Pending Management Approval'), ('PENDING_PRINCIPAL', 'Pending Principal Approval'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
