# Generated by Django 6.0.5 on 2026-08-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0005_functionrequest_previous_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionrequest',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD', 'Pending HOD Approval'), ('PENDING_DEAN', 'Pending Dean Approval'), ('PENDING_MANAGEMENT', 'Pending Management Approval'), ('PENDING_PRINCIPAL', 'Pending Principal Approval'), ('PENDING_FINAL_CONFIRMATION', 'Pending Final Confirmation'), ('RETURNED_FOR_CORRECTION', 'Returned for Correction'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30),
        ),
    ]
