# Generated by Django 6.0.5 on 2026-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0006_alter_functionrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='functionrequest',
            name='student_transport_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='functionrequest',
            name='student_transport_required',
            field=models.BooleanField(default=False),
        ),
    ]
