# Generated by Django 6.0.5 on 2026-05-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_HOD', 'Pending HOD Approval'), ('PENDING_MANAGEMENT', 'Pending Management Approval'), ('PENDING_PRINCIPAL', 'Pending Principal Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=30)),
                ('function_name', models.CharField(max_length=200)),
                ('function_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('number_of_days', models.IntegerField()),
                ('time_from', models.TimeField()),
                ('time_to', models.TimeField()),
                ('type_of_training', models.CharField(blank=True, max_length=100)),
                ('number_of_students', models.IntegerField(default=0)),
                ('class_name', models.CharField(blank=True, max_length=100)),
                ('organizer_name', models.CharField(max_length=100)),
                ('organizer_contact', models.CharField(max_length=20)),
                ('chief_guest_name', models.CharField(blank=True, max_length=100)),
                ('chief_guest_designation', models.CharField(blank=True, max_length=100)),
                ('chief_guest_organization', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.faculty')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='halls.seminarhall')),
            ],
        ),
    ]
