# Generated by Django 6.0.5 on 2026-05-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functionrequest',
            name='organizer_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
