# Generated by Django 6.0.5 on 2026-06-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_alter_functionrequest_organizer_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='functionrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='functionrequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='functionrequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='functionrequest',
            name='number_of_days',
            field=models.IntegerField(default=1),
        ),
    ]
