# Generated by Django 6.0.5 on 2026-05-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brochure', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('photos', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('attendance_sheet', models.FileField(blank=True, null=True, upload_to='attendance/')),
                ('feedback_report', models.FileField(blank=True, null=True, upload_to='feedback/')),
                ('outcome', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('function_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='requests.functionrequest')),
            ],
        ),
    ]
