# Generated by Django 6.0.5 on 2026-05-29 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='attendance_sheet',
        ),
        migrations.RemoveField(
            model_name='eventreport',
            name='photos',
        ),
        migrations.AddField(
            model_name='eventreport',
            name='alumni_contribution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='budget_actual',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='budget_proposed',
            field=models.CharField(blank=True, default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='dept_ref_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='funding_agency',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='participants_external',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='participants_internal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='iqac_photos/'),
        ),
        migrations.AddField(
            model_name='eventreport',
            name='photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='iqac_photos/'),
        ),
        migrations.CreateModel(
            name='ReportGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('organization_address', models.TextField(blank=True)),
                ('mobile', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('event_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='event_documents.eventreport')),
            ],
        ),
    ]
