# Generated by Django 6.0.5 on 2026-05-28 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestHouseRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('number_of_persons', models.IntegerField(blank=True, default=0, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('function_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guest_house', to='requests.functionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='MementoRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('honorarium_worth', models.CharField(blank=True, max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('dias_seats', models.IntegerField(default=0)),
                ('audience_seats', models.IntegerField(default=0)),
                ('table_cloths', models.IntegerField(default=0)),
                ('reception_items', models.TextField(blank=True)),
                ('function_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memento', to='requests.functionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='PowerCameraRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mic_required', models.BooleanField(default=False)),
                ('mic_type', models.CharField(blank=True, max_length=100)),
                ('number_of_mics', models.IntegerField(default=0)),
                ('ac_required', models.BooleanField(default=False)),
                ('projector_required', models.BooleanField(default=False)),
                ('laptop_required', models.BooleanField(default=False)),
                ('photographer_required', models.BooleanField(default=False)),
                ('photographer_type', models.CharField(blank=True, choices=[('LAB_TECHNICIAN', 'Lab Technician'), ('OFFICIAL', 'Official Photographer')], max_length=50)),
                ('function_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='power_camera', to='requests.functionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RefreshmentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tea_required', models.BooleanField(default=False)),
                ('coffee_required', models.BooleanField(default=False)),
                ('snacks_required', models.BooleanField(default=False)),
                ('veg_lunch_count', models.IntegerField(default=0)),
                ('non_veg_lunch_count', models.IntegerField(default=0)),
                ('tiffin_count', models.IntegerField(default=0)),
                ('required_time', models.TimeField(blank=True, null=True)),
                ('payment_through', models.CharField(blank=True, choices=[('ASSOCIATION', 'Association Account'), ('INSTITUTION', 'Institution Account')], max_length=50)),
                ('function_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refreshment', to='requests.functionrequest')),
            ],
        ),
        migrations.CreateModel(
            name='TransportRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('pickup_location', models.CharField(blank=True, max_length=200)),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('drop_time', models.TimeField(blank=True, null=True)),
                ('pickup_person_name', models.CharField(blank=True, max_length=100)),
                ('pickup_person_contact', models.CharField(blank=True, max_length=20)),
                ('function_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transport', to='requests.functionrequest')),
            ],
        ),
    ]
