# Generated by Django 6.0.5 on 2026-06-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_refreshmentrequirement_normal_lunch_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportrequirement',
            name='drop_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transportrequirement',
            name='drop_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
