# Generated by Django 6.0.5 on 2026-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_transportrequirement_drop_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshmentrequirement',
            name='lunch_required_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshmentrequirement',
            name='student_coffee_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refreshmentrequirement',
            name='student_required_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshmentrequirement',
            name='student_snacks_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refreshmentrequirement',
            name='student_tea_required',
            field=models.BooleanField(default=False),
        ),
    ]
