# Generated by Django 6.0.5 on 2026-06-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_documents', '0002_remove_eventreport_attendance_sheet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreport',
            name='attendance_sheet',
            field=models.ImageField(blank=True, null=True, upload_to='attendance/'),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='brochure',
            field=models.ImageField(blank=True, null=True, upload_to='brochures/'),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='eventreport',
            name='feedback_report',
            field=models.ImageField(blank=True, null=True, upload_to='feedback/'),
        ),
    ]
