# Generated by Django 6.0.5 on 2026-07-23 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_documents', '0003_eventreport_attendance_sheet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportguest',
            name='event_report',
        ),
        migrations.DeleteModel(
            name='EventReport',
        ),
        migrations.DeleteModel(
            name='ReportGuest',
        ),
    ]
