# Generated by Django 6.0.5 on 2026-06-11 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshmentrequirement',
            name='normal_lunch_count',
            field=models.IntegerField(default=0),
        ),
    ]
